spring.application.name=haqms

spring.profiles.active=qa

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.open-in-view=false

jwt.secret=zL70zw9GLMd88k1FP/NqXBouZm1p4LGwAIr4dgjtrZ8=
jwt.expiration-ms=3600000